version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "80:a7:0a:4d:5a:ec:a8:8b:af:aa:b1:00:0e:0c:f4:15"

      - run: ssh-keyscan cloud.kvisnia.me >> ~/.ssh/known_hosts

      - run:
          name: deploy
          working_directory: /
          command: |
            ssh kvisnia@cloud.kvisnia.me 'bash /home/kvisnia/vendure/build.sh'

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
