version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: deploy
          working_directory: /
          command: |
            ssh kvisnia@cloud.kvisnia.me 'bash /home/kvisnia/vendure/build.sh'

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
